
job_mapping = {
    "데이터 분석가": "Data Analyst",
    "백엔드 개발": "Back-end Developer",
    "서버/백엔드 개발": "Back-end Developer",
    "프론트엔드 개발": "Front-end Developer",
    "웹퍼블리셔": "Front-end Developer",
    "웹개발": "Full-stack Developer",
    "웹 개발": "Full-stack Developer",
    "클라우드 개발": "Full-stack Developer",
    "소프트웨어 개발": "Software Developer",
    "소프트웨어아키텍트": "Software Developer",
    "네트워크/보안/운영": "System Engineer",
    "DBA(Database Admin.)": "Database Administrator (DBA)",
    "iOS 개발": "Mobile Developer",
    "안드로이드 개발": "Mobile Developer",
    "데이터 사이언티스트": "AI/ML Engineer",
    "머신러닝 엔지니어": "AI/ML Engineer",
    "데이터 엔지니어": "Data Engineer",
    "빅데이터 엔지니어": "Data Engineer",
    "QA(Quality Assurance)": "QA Engineer",
    "기술지원": "Technical Support",
    "게임개발": "Game Developer",
    "VR 엔지니어": "Game Developer",
    "CTO(Chief Technology Officer)": "CTO (Chief Technology Officer)",
    "ERP": "ERP Specialist",
    "BI 엔지니어": "BI Engineer",
    "하드웨어 개발": "Hardware Developer"
}

skill_mapping = {
    "Cloud-AWS": ["AWS", "aws"],
    "Cloud-AWS S3": ["AWS S3", "Amazon S3"],
    "Cloud-AWS Lambda": ["AWS Lambda"],
    "Cloud-AWS Glue": ["AWS Glue"],
    "Cloud-AWS EC2": ["Amazon EC2", "AWS EC2"],
    "Cloud-AWS Elastic Load Balancing": ["AWS Elastic Load Balancing", "AWS Elastic Load Balancing ..."],
    "Cloud-AWS CodeCommit": ["AWS CodeCommit"],
    "Cloud-AWS Data Pipeline": ["AWS Data Pipeline"],
    "Cloud-AWS IAM": ["AWS IAM"],
    "Cloud-AWS IoT": ["AWS IoT Device Management"],
    "Cloud-AWS Storage Gateway": ["AWS Storage Gateway"],
    "Cloud-AWS X-Ray": ["AWS X-Ray"],
    "Cloud-AWS EKS": ["Amazon EKS"],
    "Cloud-AWS RDS": ["Amazon RDS"],
    "Cloud-AWS DynamoDB": ["Amazon DynamoDB","Dynamodb"],
    "Cloud-GCP": ["GCP", "Google Cloud Platform", "google cloud", "gcp"],
    "Cloud-GCP BigQuery": ["Google BigQuery"],
    "Cloud-GCP Cloud IoT": ["Google Cloud IoT Core"],
    "Cloud-GCP Load Balancing": ["Google Cloud Load Balancing"],
    "Cloud-GCP Natural Language": ["Google Cloud Natural Language"],
    "Cloud-GCP SQL": ["Google Cloud SQL", "Google Cloud SQL for Postgr..."],
    "Cloud-GCP VPC": ["Google Cloud VPC"],
    "Cloud-Azure": ["Azure", "Microsoft Azure", "azure"],
    "Cloud-Azure App Service": ["Azure App Service"],
    "Cloud-Azure IoT": ["Azure IoT Hub"],
    "Cloud-Azure DevOps": ["Azure DevOps", "Azure DevOps Server"],
    "Cloud-Azure Storage": ["Azure Storage"],
    "Cloud-Azure Synapse": ["Azure Synapse"],
    "Cloud-Azure CDN": ["Azure CDN"],
    "Cloud-Azure Application Insights": ["Azure Application Insights"],
    "Languages-Python": ["Python", "python3", "파이썬", "python"],
    "Languages-Java": ["Java", "java", "Java 8", "java ee"],
    "Languages-C#": ["C#", "c#", ".NET", ".NET Core", ".net"],
    "Languages-C++": ["c/c++", "visual c++", "C++", "c++", "C++ Builder"],
    "Languages-TypeScript": ["TypeScript", "typescript"],
    "Languages-PHP": ["PHP", "php"],
    "Languages-Kotlin": ["Kotlin", "kotlin", "KOTLIN", "코틀린"],
    "Languages-R": ["R", "r", "R Language"],
    "Languages-Ruby": ["Ruby", "ruby on rails", "ruby", "RUBY"],
    "Languages-Swift": ["Swift", "swiftui","swift","SwiftUI","RxSwift"],
    "Languages-Dart": ["Dart"],
    "Languages-SQL": ["SQL", "sql"],
    "Languages-C": ["C", "c", "C언어","Objective-C"],
    "Languages-Go": ["Golang", "Go","GO", "golang", "go"],
    "Languages-Javascript": ["Javascript", "javascript", "JS", "js","JavaScript"],
    "Languages-Rust": ["Rust",'rust'],
    "Web Frameworks-Django": ["Django", "Django REST framework", "Django framework"],
    "Web Frameworks-Flask": ["Flask", "flask"],
    "Web Frameworks-Spring": ["JSP","Spring framework", "spring boot", "Web Frameworks-Spring", "Spring", "Spring Boot", "Spring framework", "Spring Framework", "Spring Data JPA"],
    "Web Frameworks-React": ["Web Frameworks-React", "react","React", "React.js", "React Native", "React Native Seed", "React Navigation", "React Query", "React Redux", "React Router", "React Server", "React.js Boilerplate", "ReactPHP"],
    "Web Frameworks-ExpressJS": ["ExpressJS", "Express"],
    "Web Frameworks-Vue.js": ["vue","Vue.js", "VueJs", "Vue3", "Vuex"],
    "Web Frameworks-AngularJS": ["AngularJS", "Angular 2", "Angular"],
    "Web Frameworks-Next.js": ["Next.js", "next js", "NextJS", "next.js","Nuxt.js"],
    "Web Frameworks-Nest.js": ["nest js", "nest.js", "Nest js", "NestJS" ,"nestjs"],
    "Web Frameworks-Node.js": ["node.js", "node js", "Node.js", "NodeJS", "nodejs"],
    "Web Frameworks-ASP.NET": ["ASP.NET", "ASP.NET Core", "ASP.NET MVC", ".net"],
    "Web Frameworks-FastAPI": ["FastAPI"],
    "DevOps-Docker": ["Docker", "Docker Compose", "Dockerized", "Dockerrizing", "도커", "docker"],
    "DevOps-Kubernetes": ["Kubernetes", "K8S", "k8s", "쿠버네티스"],
    "DevOps-Jenkins": ["Jenkins"],
    "DevOps-Terraform": ["Terraform"],
    "DevOps-Ansible": ["Ansible"],
    "DevOps-CircleCI": ["CircleCI"],
    "DevOps-AWS CodePipeline": ["AWS CodePipeline"],
    "DevOps-DevOps": ["devops"],
    "Data Science-TensorFlow": ["TensorFlow", "Tensorflow", "tensorflow", "텐서플로우"],
    "Data Science-PyTorch": ["PyTorch", "pytorch", "PYTORCH", "Pytorch"],
    "Data Science-Pandas": ["Pandas", "pandas"],
    "Data Science-NumPy": ["NumPy", "numpy"],
    "Data Science-Scikit-learn": ["scikit-learn"],
    "Data Science-Keras": ["Keras"],
    "Database-DB": ["DB", "Database","데이터베이스"],
    "Database-QueryDSL": ["QueryDSL"],
    "Database-RDBMS": ["rdbms","RDB"],
    "Database-NoSQL": ["nosql"],
    "Database-MariaDB": ["MariaDB", "MARIADB", "mariadb", "mariaDB", "Mariadb", "maria", "maria db"],
    "Database-MySQL": ["MySQL", "mysql", "MySQL WorkBench", "MYSQL"],
    "Database-PostgreSQL": ["postgres","PostgreSQL", "postgresql", "PostGIS"],
    "Database-MongoDB": ["MongoDB", "Mongoose"],
    "Database-Redis": ["Redis", "redis","redis cloud","REDIS"],
    "Database-Mybatis": ["Mybatis"],
    "Database-Cassandra": ["Cassandra"],
    "Database-MSSQL": ["MSSQL", "Microsoft SQL Server", "sql server"],
    "Database-Oracle": ["Oracle", "Oracle PL/SQL", "Oracle DB", "Oracle Integration Cloud","오라클"],
    "Database-SQLite": ["SQLite", "SQLAlchemy"],
    "Database-Elasticsearch": ["Elasticsearch"],
    "Database-GraphQL": ["GraphQL"],
    "Mobile Development-Android": ["Android SDK", "Android OS", "android studio","안드로이드 앱 개발","android","안드로이드"],
    "Mobile Development-iOS": ["iOS", "ios", "iOS 개발","iOS 앱개발"],
    "Mobile Development-Flutter": ["Flutter"],
    "Mobile Development-React Native": ["React Native"],
    "Networking-Network": ["네트워크","FW","Network"],
    "Networking-Firewall": ["Firewall"],
    "Networking-VPN": ["VPN"],
    "Networking-Cisco": ["Cisco", "Cisco ISE"],
    "Networking-TCP/IP": ["TCP/IP", "tcpip"],
    "Networking-Router": ["Router"],
    "Tools-Figma": ["Figma"],
    "Tools-Photoshop": ["Adobe Photoshop"],
    "Tools-Jira": ["Jira", "JIRA", "jira", "지라"],
    "Tools-Confluence": ["Confluence"],
    "Tools-Slack": ["Slack", "SLACK", "slack", "슬랙"],
    "Tools-Sketch": ["Sketch"],
    "Tools-Trello": ["Trello", "TRELLO", "트렐로"],
    "Tools-Notion": ["Notion", "노션", "notion"],
    "Frontend-HTML": ["HTML5", "HTML", "html5"],
    "Frontend-CSS": ["CSS3", "CSS 3", "css", "CSS"],
    "Frontend-Sass": ["Sass"],
    "Frontend-Bootstrap": ["Bootstrap"],
    "Frontend-jQuery": ["jQuery","jquery"],
    "Frontend-TailwindCSS": ["TailwindCSS"],
    "AI-Deep Learning": ["Deep Learning", "딥러닝", "DeepLearning", "AI", "AI/인공지능","인공지능"],
    "AI-Machine Learning": ["machine learning", "Machine Learning", "머신러닝", "MachineLearning",'ml',"MLOPS"],
    "AI-NLP": ["NLP", "자연어처리", "LLM"],
    "Blockchain-Blockchain": ["Blockchain",],
    "Blockchain-Solidity": ["Solidity"],
    "Blockchain-Hyperledger": ["Hyperledger Fabric", "Hyperledger Indy"],
    "Blockchain-Ethereum": ["Ethereum", "etherscan"],
    "Version Control-Git": ["git", "Git", "github", "GitHub", "GitHub Actions", "GitLab", "Bitbucket", "Git Flow"],
    "Other-Spring Framework": ["Spring", "Spring Boot"],
    "Other-REST API": ["REST API", "RESTful", "rest api", "restful api"],
    "Other-Socket": ["Socket.IO", "SocketCluster","WebSocket"],
    "Other-Prometheus": ["Prometheus"],
    "Other-OpenAPI": ["OpenAPI"],
    "Other-Softskills": ["비즈니스 영어","영어","한국어","외국어(영어)" ],
    "Other-Development": ["Algorithm","알고리즘 개발","개발","알고리즘","소프트웨어개발","이슈관리","플랫폼개발","시스템구축","서버","웹개발","서비스개발","Android 개발","펌웨어 개발","백엔드 개발","프론트엔드 개발","응용프로그램개발","어플리케이션 개발"],
    "Other-HW": ["하드웨어", "HW", "hw","hw설계"],
    "Other-SW": ["소프트웨어", "SW", "sw"],
    "Other-Embedded": ["Embedded","MCU","RTOS","임베디드","임베디드 시스템"],
    "Other-Security": ["보안", "정보보안", "보안운영"],
    "Other-Image Processing": ["영상처리", "CUDA", "3D Rendering","3d","unity3d"],
    "Other-PCB": ["PCB설계", "PCB"],
    "Other-Webpack": ["Webpack", "webpack"],
    "Other-VS Code": ["Visual Studio Code", "Visual Studio"],
    "OS-Linux": ["Linux", "Ubuntu", "CentOS", "LINUX", "리눅스", "linux-kernel","Embedded Linux","linux kernel"],
    "OS-Windows": ["Windows Server", "Windows","windows", "window","윈도우"],
    "Data Process-Kafka": ["Kafka"],
    "Data Process-Airflow": ["Airflow", "Apache Airflow", "airflow", "apache airflow"],
    "Data Process-Spark": ["spark", "Apache Spark", "Spark", "SPARK"],
    "Data Process-Hadoop": ["Hadoop"],
    "Data Analysis-Data Analysis": ["데이터분석","데이터 분석", "빅데이터 분석","빅데이터","BigData","인사이트 도출"],
    "Data Analysis-MATLAB": ["MATLAB","matlab" ],
    "Data Analysis-Tableau": ["Tableau"],
    "Computer Vision-OpenCV": ["OpenCV"]
}